language: python

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y socat
  - sudo pip install pyserial nose coverage

script:
  - nosetests --with-coverage --cover-package=serial_mock tests

